class Sura {
  String snameAr;
  String nameEn;
  String numberOfVerses;
  String fileName;
  int suraIndex;

  Sura({
    required this.snameAr,
    required this.nameEn,
    required this.numberOfVerses,
    required this.fileName,
    required this.suraIndex,
  });

  static List<Sura> getSurasList() => [
        Sura(
            snameAr: "الفاتحه",
            nameEn: "Al-Fatiha",
            numberOfVerses: "7",
            fileName: "1.txt",
            suraIndex: 0),
        Sura(
            snameAr: "البقرة",
            nameEn: "Al-Baqarah",
            numberOfVerses: "286",
            fileName: "2.txt",
            suraIndex: 1),
        Sura(
            snameAr: "آل عمران",
            nameEn: "Aal-E-Imran",
            numberOfVerses: "200",
            fileName: "3.txt",
            suraIndex: 2),
        Sura(
            snameAr: "النساء",
            nameEn: "An-Nisa'",
            numberOfVerses: "176",
            fileName: "4.txt",
            suraIndex: 3),
        Sura(
            snameAr: "المائدة",
            nameEn: "Al-Ma'idah",
            numberOfVerses: "120",
            fileName: "5.txt",
            suraIndex: 4),
        Sura(
            snameAr: "الأنعام",
            nameEn: "Al-An'am",
            numberOfVerses: "165",
            fileName: "6.txt",
            suraIndex: 5),
        Sura(
            snameAr: "الأعراف",
            nameEn: "Al-A'raf",
            numberOfVerses: "206",
            fileName: "7.txt",
            suraIndex: 6),
        Sura(
            snameAr: "الأنفال",
            nameEn: "Al-Anfal",
            numberOfVerses: "75",
            fileName: "8.txt",
            suraIndex: 7),
        Sura(
            snameAr: "التوبة",
            nameEn: "At-Tawbah",
            numberOfVerses: "129",
            fileName: "9.txt",
            suraIndex: 8),
        Sura(
            snameAr: "يونس",
            nameEn: "Yunus",
            numberOfVerses: "109",
            fileName: "10.txt",
            suraIndex: 9),
        Sura(
            snameAr: "هود",
            nameEn: "Hud",
            numberOfVerses: "123",
            fileName: "11.txt",
            suraIndex: 10),
        Sura(
            snameAr: "يوسف",
            nameEn: "Yusuf",
            numberOfVerses: "111",
            fileName: "12.txt",
            suraIndex: 11),
        Sura(
            snameAr: "الرعد",
            nameEn: "Ar-Ra'd",
            numberOfVerses: "43",
            fileName: "13.txt",
            suraIndex: 12),
        Sura(
            snameAr: "إبراهيم",
            nameEn: "Ibrahim",
            numberOfVerses: "52",
            fileName: "14.txt",
            suraIndex: 13),
        Sura(
            snameAr: "الحجر",
            nameEn: "Al-Hijr",
            numberOfVerses: "99",
            fileName: "15.txt",
            suraIndex: 14),
        Sura(
            snameAr: "النحل",
            nameEn: "An-Nahl",
            numberOfVerses: "128",
            fileName: "16.txt",
            suraIndex: 15),
        Sura(
            snameAr: "الإسراء",
            nameEn: "Al-Isra",
            numberOfVerses: "111",
            fileName: "17.txt",
            suraIndex: 16),
        Sura(
            snameAr: "الكهف",
            nameEn: "Al-Kahf",
            numberOfVerses: "110",
            fileName: "18.txt",
            suraIndex: 17),
        Sura(
            snameAr: "مريم",
            nameEn: "Maryam",
            numberOfVerses: "98",
            fileName: "19.txt",
            suraIndex: 18),
        Sura(
            snameAr: "طه",
            nameEn: "Ta-Ha",
            numberOfVerses: "135",
            fileName: "20.txt",
            suraIndex: 19),
        Sura(
            snameAr: "الأنبياء",
            nameEn: "Al-Anbiya",
            numberOfVerses: "112",
            fileName: "21.txt",
            suraIndex: 20),
        Sura(
            snameAr: "الحج",
            nameEn: "Al-Hajj",
            numberOfVerses: "78",
            fileName: "22.txt",
            suraIndex: 21),
        Sura(
            snameAr: "المؤمنون",
            nameEn: "Al-Mu'minun",
            numberOfVerses: "118",
            fileName: "23.txt",
            suraIndex: 22),
        Sura(
            snameAr: "النّور",
            nameEn: "An-Nur",
            numberOfVerses: "64",
            fileName: "24.txt",
            suraIndex: 23),
        Sura(
            snameAr: "الفرقان",
            nameEn: "Al-Furqan",
            numberOfVerses: "77",
            fileName: "25.txt",
            suraIndex: 24),
        Sura(
            snameAr: "الشعراء",
            nameEn: "Ash-Shu'ara",
            numberOfVerses: "227",
            fileName: "26.txt",
            suraIndex: 25),
        Sura(
            snameAr: "النّمل",
            nameEn: "An-Naml",
            numberOfVerses: "93",
            fileName: "27.txt",
            suraIndex: 26),
        Sura(
            snameAr: "القصص",
            nameEn: "Al-Qasas",
            numberOfVerses: "88",
            fileName: "28.txt",
            suraIndex: 27),
        Sura(
            snameAr: "العنكبوت",
            nameEn: "Al-Ankabut",
            numberOfVerses: "69",
            fileName: "29.txt",
            suraIndex: 28),
        Sura(
            snameAr: "الرّوم",
            nameEn: "Ar-Rum",
            numberOfVerses: "60",
            fileName: "30.txt",
            suraIndex: 29),
        Sura(
            snameAr: "لقمان",
            nameEn: "Luqman",
            numberOfVerses: "34",
            fileName: "31.txt",
            suraIndex: 30),
        Sura(
            snameAr: "السجدة",
            nameEn: "As-Sajda",
            numberOfVerses: "30",
            fileName: "32.txt",
            suraIndex: 31),
        Sura(
            snameAr: "الأحزاب",
            nameEn: "Al-Ahzab",
            numberOfVerses: "73",
            fileName: "33.txt",
            suraIndex: 32),
        Sura(
            snameAr: "سبأ",
            nameEn: "Saba",
            numberOfVerses: "54",
            fileName: "34.txt",
            suraIndex: 33),
        Sura(
            snameAr: "فاطر",
            nameEn: "Fatir",
            numberOfVerses: "45",
            fileName: "35.txt",
            suraIndex: 34),
        Sura(
            snameAr: "يس",
            nameEn: "Ya-Sin",
            numberOfVerses: "83",
            fileName: "36.txt",
            suraIndex: 35),
        Sura(
            snameAr: "الصافات",
            nameEn: "As-Saffat",
            numberOfVerses: "182",
            fileName: "37.txt",
            suraIndex: 36),
        Sura(
            snameAr: "ص",
            nameEn: "Sad",
            numberOfVerses: "88",
            fileName: "38.txt",
            suraIndex: 37),
        Sura(
            snameAr: "الزمر",
            nameEn: "Az-Zumar",
            numberOfVerses: "75",
            fileName: "39.txt",
            suraIndex: 38),
        Sura(
            snameAr: "غافر",
            nameEn: "Ghafir",
            numberOfVerses: "85",
            fileName: "40.txt",
            suraIndex: 39),
        Sura(
            snameAr: "فصّلت",
            nameEn: "Fussilat",
            numberOfVerses: "54",
            fileName: "41.txt",
            suraIndex: 40),
        Sura(
            snameAr: "الشورى",
            nameEn: "Ash-Shura",
            numberOfVerses: "53",
            fileName: "42.txt",
            suraIndex: 41),
        Sura(
            snameAr: "الزخرف",
            nameEn: "Az-Zukhruf",
            numberOfVerses: "89",
            fileName: "43.txt",
            suraIndex: 42),
        Sura(
            snameAr: "الدّخان",
            nameEn: "Ad-Dukhan",
            numberOfVerses: "59",
            fileName: "44.txt",
            suraIndex: 43),
        Sura(
            snameAr: "الجاثية",
            nameEn: "Al-Jathiya",
            numberOfVerses: "37",
            fileName: "45.txt",
            suraIndex: 44),
        Sura(
            snameAr: "الأحقاف",
            nameEn: "Al-Ahqaf",
            numberOfVerses: "35",
            fileName: "46.txt",
            suraIndex: 45),
        Sura(
            snameAr: "محمد",
            nameEn: "Muhammad",
            numberOfVerses: "38",
            fileName: "47.txt",
            suraIndex: 46),
        Sura(
            snameAr: "الفتح",
            nameEn: "Al-Fath",
            numberOfVerses: "29",
            fileName: "48.txt",
            suraIndex: 47),
        Sura(
            snameAr: "الحجرات",
            nameEn: "Al-Hujurat",
            numberOfVerses: "18",
            fileName: "49.txt",
            suraIndex: 48),
        Sura(
            snameAr: "ق",
            nameEn: "Qaf",
            numberOfVerses: "45",
            fileName: "50.txt",
            suraIndex: 49),
        Sura(
            snameAr: "الذاريات",
            nameEn: "Adh-Dhariyat",
            numberOfVerses: "60",
            fileName: "51.txt",
            suraIndex: 50),
        Sura(
            snameAr: "الطور",
            nameEn: "At-Tur",
            numberOfVerses: "49",
            fileName: "52.txt",
            suraIndex: 51),
        Sura(
            snameAr: "النجم",
            nameEn: "An-Najm",
            numberOfVerses: "62",
            fileName: "53.txt",
            suraIndex: 52),
        Sura(
            snameAr: "القمر",
            nameEn: "Al-Qamar",
            numberOfVerses: "55",
            fileName: "54.txt",
            suraIndex: 53),
        Sura(
            snameAr: "الرحمن",
            nameEn: "Ar-Rahman",
            numberOfVerses: "78",
            fileName: "55.txt",
            suraIndex: 54),
        Sura(
            snameAr: "الواقعة",
            nameEn: "Al-Waqi'a",
            numberOfVerses: "96",
            fileName: "56.txt",
            suraIndex: 55),
        Sura(
            snameAr: "الحديد",
            nameEn: "Al-Hadid",
            numberOfVerses: "29",
            fileName: "57.txt",
            suraIndex: 56),
        Sura(
            snameAr: "المجادلة",
            nameEn: "Al-Mujadila",
            numberOfVerses: "22",
            fileName: "58.txt",
            suraIndex: 57),
        Sura(
            snameAr: "الحشر",
            nameEn: "Al-Hashr",
            numberOfVerses: "24",
            fileName: "59.txt",
            suraIndex: 58),
        Sura(
            snameAr: "الممتحنة",
            nameEn: "Al-Mumtahina",
            numberOfVerses: "13",
            fileName: "60.txt",
            suraIndex: 59),
        Sura(
            snameAr: "الصف",
            nameEn: "As-Saff",
            numberOfVerses: "14",
            fileName: "61.txt",
            suraIndex: 60),
        Sura(
            snameAr: "الجمعة",
            nameEn: "Al-Jumu'a",
            numberOfVerses: "11",
            fileName: "62.txt",
            suraIndex: 61),
        Sura(
            snameAr: "المنافقون",
            nameEn: "Al-Munafiqun",
            numberOfVerses: "11",
            fileName: "63.txt",
            suraIndex: 62),
        Sura(
            snameAr: "التغابن",
            nameEn: "At-Taghabun",
            numberOfVerses: "18",
            fileName: "64.txt",
            suraIndex: 63),
        Sura(
            snameAr: "الطلاق",
            nameEn: "At-Talaq",
            numberOfVerses: "12",
            fileName: "65.txt",
            suraIndex: 64),
        Sura(
            snameAr: "التحريم",
            nameEn: "At-Tahrim",
            numberOfVerses: "12",
            fileName: "66.txt",
            suraIndex: 65),
        Sura(
            snameAr: "الملك",
            nameEn: "Al-Mulk",
            numberOfVerses: "30",
            fileName: "67.txt",
            suraIndex: 66),
        Sura(
            snameAr: "القلم",
            nameEn: "Al-Qalam",
            numberOfVerses: "52",
            fileName: "68.txt",
            suraIndex: 67),
        Sura(
            snameAr: "الحاقة",
            nameEn: "Al-Haqqah",
            numberOfVerses: "52",
            fileName: "69.txt",
            suraIndex: 68),
        Sura(
            snameAr: "المعارج",
            nameEn: "Al-Ma'arij",
            numberOfVerses: "44",
            fileName: "70.txt",
            suraIndex: 69),
        Sura(
            snameAr: "نوح",
            nameEn: "Nuh",
            numberOfVerses: "28",
            fileName: "71.txt",
            suraIndex: 70),
        Sura(
            snameAr: "الجن",
            nameEn: "Al-Jinn",
            numberOfVerses: "28",
            fileName: "72.txt",
            suraIndex: 71),
        Sura(
            snameAr: "المزمل",
            nameEn: "Al-Muzzammil",
            numberOfVerses: "20",
            fileName: "73.txt",
            suraIndex: 72),
        Sura(
            snameAr: "المدثر",
            nameEn: "Al-Muddathir",
            numberOfVerses: "56",
            fileName: "74.txt",
            suraIndex: 73),
        Sura(
            snameAr: "القيامة",
            nameEn: "Al-Qiyama",
            numberOfVerses: "40",
            fileName: "75.txt",
            suraIndex: 74),
        Sura(
            snameAr: "الإنسان",
            nameEn: "Al-Insan",
            numberOfVerses: "31",
            fileName: "76.txt",
            suraIndex: 75),
        Sura(
            snameAr: "المرسلات",
            nameEn: "Al-Mursalat",
            numberOfVerses: "50",
            fileName: "77.txt",
            suraIndex: 76),
        Sura(
            snameAr: "النبأ",
            nameEn: "An-Naba",
            numberOfVerses: "40",
            fileName: "78.txt",
            suraIndex: 77),
        Sura(
            snameAr: "النازعات",
            nameEn: "An-Nazi'at",
            numberOfVerses: "46",
            fileName: "79.txt",
            suraIndex: 78),
        Sura(
            snameAr: "عبس",
            nameEn: "Abasa",
            numberOfVerses: "42",
            fileName: "80.txt",
            suraIndex: 79),
        Sura(
            snameAr: "التكوير",
            nameEn: "At-Takwir",
            numberOfVerses: "29",
            fileName: "81.txt",
            suraIndex: 80),
        Sura(
            snameAr: "الإنفطار",
            nameEn: "Al-Infitar",
            numberOfVerses: "19",
            fileName: "82.txt",
            suraIndex: 81),
        Sura(
            snameAr: "المطففين",
            nameEn: "Al-Mutaffifin",
            numberOfVerses: "36",
            fileName: "83.txt",
            suraIndex: 82),
        Sura(
            snameAr: "الإنشقاق",
            nameEn: "Al-Inshiqaq",
            numberOfVerses: "25",
            fileName: "84.txt",
            suraIndex: 83),
        Sura(
            snameAr: "البروج",
            nameEn: "Al-Buruj",
            numberOfVerses: "22",
            fileName: "85.txt",
            suraIndex: 84),
        Sura(
            snameAr: "الطارق",
            nameEn: "At-Tariq",
            numberOfVerses: "17",
            fileName: "86.txt",
            suraIndex: 85),
        Sura(
            snameAr: "الأعلى",
            nameEn: "Al-A'la",
            numberOfVerses: "19",
            fileName: "87.txt",
            suraIndex: 86),
        Sura(
            snameAr: "الغاشية",
            nameEn: "Al-Ghashiya",
            numberOfVerses: "26",
            fileName: "88.txt",
            suraIndex: 87),
        Sura(
            snameAr: "الفجر",
            nameEn: "Al-Fajr",
            numberOfVerses: "30",
            fileName: "89.txt",
            suraIndex: 88),
        Sura(
            snameAr: "البلد",
            nameEn: "Al-Balad",
            numberOfVerses: "15",
            fileName: "90.txt",
            suraIndex: 89),
        Sura(
            snameAr: "الشمس",
            nameEn: "Ash-Shams",
            numberOfVerses: "15",
            fileName: "91.txt",
            suraIndex: 90),
        Sura(
            snameAr: "الليل",
            nameEn: "Al-Lail",
            numberOfVerses: "21",
            fileName: "92.txt",
            suraIndex: 91),
        Sura(
            snameAr: "الضحى",
            nameEn: "Ad-Duha",
            numberOfVerses: "11",
            fileName: "93.txt",
            suraIndex: 92),
        Sura(
            snameAr: "الشرح",
            nameEn: "Ash-Sharh",
            numberOfVerses: "8",
            fileName: "94.txt",
            suraIndex: 93),
        Sura(
            snameAr: "التين",
            nameEn: "At-Tin",
            numberOfVerses: "8",
            fileName: "95.txt",
            suraIndex: 94),
        Sura(
            snameAr: "العلق",
            nameEn: "Al-Alaq",
            numberOfVerses: "19",
            fileName: "96.txt",
            suraIndex: 95),
        Sura(
            snameAr: "القدر",
            nameEn: "Al-Qadr",
            numberOfVerses: "5",
            fileName: "97.txt",
            suraIndex: 96),
        Sura(
            snameAr: "البينة",
            nameEn: "Al-Bayyina",
            numberOfVerses: "8",
            fileName: "98.txt",
            suraIndex: 97),
        Sura(
            snameAr: "الزلزلة",
            nameEn: "Az-Zalzalah",
            numberOfVerses: "8",
            fileName: "99.txt",
            suraIndex: 98),
        Sura(
            snameAr: "العاديات",
            nameEn: "Al-Adiyat",
            numberOfVerses: "11",
            fileName: "100.txt",
            suraIndex: 99),
        Sura(
            snameAr: "القارعة",
            nameEn: "Al-Qari'a",
            numberOfVerses: "11",
            fileName: "101.txt",
            suraIndex: 100),
        Sura(
            snameAr: "التكاثر",
            nameEn: "At-Takathur",
            numberOfVerses: "8",
            fileName: "102.txt",
            suraIndex: 101),
        Sura(
            snameAr: "العصر",
            nameEn: "Al-Asr",
            numberOfVerses: "3",
            fileName: "103.txt",
            suraIndex: 102),
        Sura(
            snameAr: "الهمزة",
            nameEn: "Al-Humazah",
            numberOfVerses: "9",
            fileName: "104.txt",
            suraIndex: 103),
        Sura(
            snameAr: "الفيل",
            nameEn: "Al-Fil",
            numberOfVerses: "5",
            fileName: "105.txt",
            suraIndex: 104),
        Sura(
            snameAr: "قريش",
            nameEn: "Quraysh",
            numberOfVerses: "4",
            fileName: "106.txt",
            suraIndex: 105),
        Sura(
            snameAr: "الماعون",
            nameEn: "Al-Ma'un",
            numberOfVerses: "7",
            fileName: "107.txt",
            suraIndex: 106),
        Sura(
            snameAr: "الكوثر",
            nameEn: "Al-Kawthar",
            numberOfVerses: "3",
            fileName: "108.txt",
            suraIndex: 107),
        Sura(
            snameAr: "الكافرون",
            nameEn: "Al-Kafirun",
            numberOfVerses: "6",
            fileName: "109.txt",
            suraIndex: 108),
        Sura(
            snameAr: "النصر",
            nameEn: "An-Nasr",
            numberOfVerses: "3",
            fileName: "110.txt",
            suraIndex: 109),
        Sura(
            snameAr: "المسد",
            nameEn: "Al-Masad",
            numberOfVerses: "5",
            fileName: "111.txt",
            suraIndex: 110),
        Sura(
            snameAr: "الإخلاص",
            nameEn: "Al-Ikhlas",
            numberOfVerses: "4",
            fileName: "112.txt",
            suraIndex: 111),
        Sura(
            snameAr: "الفلق",
            nameEn: "Al-Falaq",
            numberOfVerses: "5",
            fileName: "113.txt",
            suraIndex: 112),
        Sura(
            snameAr: "الناس",
            nameEn: "An-Nas",
            numberOfVerses: "6",
            fileName: "114.txt",
            suraIndex: 113)
      ];
}
